### ISSUE TITLE
License and py3 clarification

### ISSUE THREAD

**Issue by sanjayankur31** [AllenInstitute/dipde#10]
Hello,

These queries came up when we were working on [including dipde in NeuroFedora](https://pagure.io/neuro-sig/NeuroFedora/issue/225).

- Is dipde made available under a GPLv3+ license? The setup.py file has a GPLv3+ header, as do other source files do, but `setup.py` says `'License :: Apache Software License :: 2.0',`
- Also, does dipde support python3? It seems to install fine in a python3 virtual environment, but `set.py` says python 2.7 only.

Thanks very much!

**Comment by sanjayankur31** [comment]
Ah, no, I double-checked: it does not install without errors on python3.

**Comment by sanjayankur31** [comment]
Hi there,

Any updates/comments here please? Is dipde still being maintained?

Cheers!

**Comment by sanjayankur31** [comment]
Friendly ping?

**Comment by nicain** [comment]
Thanks for reaching out @sanjayankur31.  To my knowledge (as of today), there is no maintainer, or maintenance plan for DiPDE at the Allen Institute.

**Comment by sanjayankur31** [comment]
Thanks for letting us know @nicain. Do you think it's worth adding a note in the Readme to ensure users that may be considering dipde are aware of the situation?

I'll close this ticket, now.
